version: "3.9"
services:

################################### kafdrop + kafka ###################################
  kafdrop:
      image: obsidiandynamics/kafdrop
      restart: "no"
      ports:
        - "9000:9000"
      environment:
        KAFKA_BROKERCONNECT: "kafka:29092"
      depends_on:
        - "kafka"
  kafka:
    external_links:
      - kafdrop
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

################################### user_service : 3001 ###################################
  user_service:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: user_service:latest
    ports:
      - '3001:3000'
    environment:
      KAFKA_BOOSTRAP_SERVERS: kafka:29092
      KAFKA_GROUP_ID: user
      PORT: 3001
      NODE_ENV: developer
    volumes:
      - ./user/src:/usr/src/app/src
    depends_on:
      - db_user_service
      - kafka

  db_user_service:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=user_service
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123
    volumes:
      - mysql_data_user_service:/var/lib/mysql

################################## authentication_service : 3000 ###################################
  authentication_service:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    image: authentication_service:latest
    ports:
      - "3000:3000"
    environment:
      KAFKA_BOOSTRAP_SERVERS: kafka:29092
      KAFKA_GROUP_ID: authentication
      PORT: 3000
      NODE_ENV: developer
    volumes:
      - ./authentication/src:/usr/src/app/src
    depends_on:
      - db_user_service
      - kafka

volumes:
  mysql_data_user_service: